---
title: "Repeated Measures ANOVA"
author: "Denise J. Roth"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(rio)
library(dplyr)
library (reshape2)
library(stats)
library(sjmisc)
library(ez)
library(nlme)
library(emmeans)
```


```{r}
d <- import("/Users/deniseroth/Downloads/Native advertisement - pretest wide.sav")


# Add a participant id to the dataframe
d_id <- d %>%
  mutate(id = row_number())


#Convert colums Cleb_Congruence_1 to Cleb_Congruence_5 as numeric, and Condition_Couple as #factor 
d_id <- d_id %>%
  mutate(across(c(Cleb_Congruence_1, Cleb_Congruence_2, 
                 Cleb_Congruence_3, Cleb_Congruence_4, 
                 Cleb_Congruence_5, Condition_Couple), as.numeric)) %>%
  mutate(across(c(Condition_Couple,id), as.factor))


# convert dataframe from wide to long format
d_long<- melt(d_id,id.vars=c("id", "Condition_Couple"),
measure.vars=c("Cleb_Congruence_1", "Cleb_Congruence_2","Cleb_Congruence_3", "Cleb_Congruence_4","Cleb_Congruence_5"),
          variable.name="Cleb_Congruence", 
          value.name="brand")




# Perform repeated measure analysis 
library (ez)
rm2<-ezANOVA(data=d_long, dv=brand, wid=.(id), within=.(Cleb_Congruence),between=.(Condition_Couple),
            detailed=TRUE,type=3, return_aov = TRUE)
print(rm2)

#perform the pairwise post hoc test
pt<-pairwise.t.test (d_long$brand, d_long$Cleb_Congruence,paired=TRUE, p.adjust.method="bonferroni")
pt

#The Muliti Level approach 

#In a multi level it is assumed that scores come from the same entities (in this case the variable id) and the scores are therefore correlated.  So, one can use the the the multi level approach using the package  Lineair Mixed Effecs Models "lme"  from the nlme package.
#It is assumed that there is variability in participants in brand scores for Celebrity Congruence the model takes into account that the predictor Celebrity Congruence is made up of data from the same participants. 

# See: Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. SAGE.

library(nlme)
lme <- lme(brand ~ Cleb_Congruence + Cleb_Congruence*Condition_Couple, random = ~1|id/Cleb_Congruence, data = d_long, method = "ML")
summary(lme)

#Perform a contrast analysis
library(emmeans)
emmeans(lme, pairwise ~ Cleb_Congruence)
emmeans(lme, pairwise ~ Cleb_Congruence | Condition_Couple)

```



